CREATE TABLE agendamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    servico_id BIGINT NOT NULL,
    data_hora_inicio TIMESTAMP NOT NULL,
    data_hora_fim TIMESTAMP NOT NULL
);

CREATE INDEX idx_agendamentos_servico_periodo ON agendamentos(servico_id, data_hora_inicio, data_hora_fim);
CREATE INDEX idx_agendamentos_usuario ON agendamentos(usuario_id);
