CREATE TABLE disponibilidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia_semana INTEGER NOT NULL CHECK (dia_semana BETWEEN 1 AND 7),
    hora_inicio TIME NOT NULL,
    hora_fim TIME NOT NULL,
    CONSTRAINT chk_horario_disponibilidade CHECK (hora_fim > hora_inicio)
);

INSERT INTO disponibilidades (dia_semana, hora_inicio, hora_fim) VALUES
    (1, '09:00', '18:00'),
    (2, '09:00', '18:00'),
    (3, '09:00', '18:00'),
    (4, '09:00', '18:00'),
    (5, '09:00', '18:00');
