CREATE TABLE IF NOT EXISTS disponibilidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia_semana INTEGER NOT NULL CHECK (dia_semana BETWEEN 1 AND 7),
    hora_inicio TIME NOT NULL,
    hora_fim TIME NOT NULL,
    CONSTRAINT chk_horario_disponibilidade CHECK (hora_fim > hora_inicio)
);

INSERT INTO disponibilidades (dia_semana, hora_inicio, hora_fim)
SELECT * FROM (
    SELECT 1, '09:00'::time, '18:00'::time UNION ALL
    SELECT 2, '09:00'::time, '18:00'::time UNION ALL
    SELECT 3, '09:00'::time, '18:00'::time UNION ALL
    SELECT 4, '09:00'::time, '18:00'::time UNION ALL
    SELECT 5, '09:00'::time, '18:00'::time
) AS v
WHERE NOT EXISTS (SELECT 1 FROM disponibilidades);
