CREATE TABLE IF NOT EXISTS profissionais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL
);

INSERT INTO profissionais (id, nome)
SELECT 1, 'Profissional Padrão'
WHERE NOT EXISTS (SELECT 1 FROM profissionais WHERE id = 1);
